postprocessor_pipeline: # set by postprocessor_pipeline_name
  # Fill holes in the map with inpainting.
  - name: inpaint
    type: gridMapCv/InpaintFilter
    params:
      input_layer: elevation
      output_layer: elevation_inpainted
      radius: 0.1

  # Compute Surface normals
  - name: surface_normals
    type: gridMapFilters/NormalVectorsFilter
    params:
      input_layer: elevation_inpainted
      output_layers_prefix: normal_vectors_
      radius: 0.2
      normal_vector_positive_axis: z

  # Compute slope map
  - name: slope
    type: gridMapFilters/MathExpressionFilter
    params:
      output_layer: slope
      expression: sqrt(normal_vectors_x^2 + normal_vectors_y^2)
      algorithm: area
      parallelization_enabled: false

  # Traversability analysis
  - name: traversability
    type: gridMapFilters/ThresholdFilter
    params:
      input_layer: slope
      output_layer: traversability
      upper_threshold: 0.5
      set_to: 1.0 # 1.0 for traversable, 0.0 for non-traversable

  #  Delete layers that are not needed to reduce bandwidth
  #  - name: delete_original_layers
  #    type: gridMapFilters/DeletionFilter
  #    params:
  #      layers: [lowest_scan_point,sensor_x_at_lowest_scan, sensor_y_at_lowest_scan, sensor_z_at_lowest_scan] # List of layers.